# Generated by Django 4.1 on 2024-04-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcs', '0002_studentinfo_imgurl_studentinfo_studentid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='student_info',
        ),
    ]
