# Generated by Django 4.1 on 2024-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcs', '0003_rename_studentinfo_student_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('StudentID', models.CharField(default='xxx', max_length=10, verbose_name='学号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='识别时间')),
            ],
        ),
    ]
